swagger: '2.0'
info:
  version: v1
  title: HadoopAsAService
  description: 'This service can be used to request for Hadoop storage along with facilities for data processing, reporting, monitoring and controls.'
host: newhadoopcluster.com:8343
basePath: /hadoopApi/v1
schemes:
- https
- http
paths:
  /api/hadoop/RequestHadoopStorage:
    post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_RequestHadoopStorage
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/HadoopStorageRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/HadoopStorageResponse'
       summary: RequestHadoopStorage
   /api/hadoop/ManageServiceAccounts:
    post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageServiceAccounts
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/ServiceAccountsRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/ServiceAccountsResponse'
       summary: ManageServiceAccounts
    /api/hadoop/ManageUsers:
     post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageUsers
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/UsersRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/UsersResponse'
       summary: ManageUsers
    /api/hadoop/ManageStorage:
     post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageStorage
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/StorageRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/StorageResponse'
       summary: ManageStorage
    /api/hadoop/ManageCompute:
     post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageCompute
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/ComputeRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/ComputeResponse'
       summary: ManageCompute
    
   
      
