swagger: '2.0'
info:
  version: v1
  title: HadoopAsAService
  description: 'This service can be used to request for Hadoop storage along with facilities for data processing, reporting, monitoring and controls.'
host: newhadoopcluster.com:8343
basePath: /hadoopApi/v1
schemes:
- https
- http
paths:
  /api/hadoop/RequestHadoopStorage:
    post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_RequestHadoopStorage
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/HadoopStorageRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/HadoopStorageResponse'
       summary: RequestHadoopStorage
   /api/hadoop/ManageServiceAccounts:
    post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageServiceAccounts
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/ServiceAccountsRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/ServiceAccountsResponse'
       summary: ManageServiceAccounts
    /api/hadoop/ManageUsers:
     post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageUsers
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/UsersRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/UsersResponse'
       summary: ManageUsers
    /api/hadoop/ManageStorage:
     post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageStorage
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/StorageRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/StorageResponse'
       summary: ManageStorage
    /api/hadoop/ManageCompute:
     post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageCompute
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/ComputeRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/ComputeResponse'
       summary: ManageCompute
    /api/hadoop/ManageCluster:
     post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageCluster
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/ManageClusterRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/ManageClusterResponse'
       summary: ManageCluster
  /api/hadoop/ManageClusterFeatures:
     post:
      tags:
      - HadoopAPI
      operationId: HadopAPI_ManageClusterFeatures
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: req
        in: body
        required: true
        schema:
          $ref: '#/definitions/ClusterFeaturesRequest'
      responses:
        '200': 
          description: OK
          schema:
            $ref: '#/definitions/ClusterFeaturesResponse'
       summary: ManageClusterFeatures
   definitions:
      HadoopStorageRequest:
        type: object
        properties:
          appId:
            desscription: Application id of the requester app
            type: string
          prod:
            description: Whether this is to store prod or non-prod data
            type: boolean
          storagespace:
            description: The storage space required in GB
            type: string
          compute:
            description: Compute capacity needed for the cluster
            type: string
          advisoryQuota:
            description: Specify the storage utilization limit when alerts needs to be sent
            type: string
          entitlement:
            description: Entitlements needed for the data
            type: string
        ServiceAccountsRequest:
          type: object
          properties:
            clusterName: 
              description: Name of the Hadoop cluster returned in request hadoop storage service
              type: string
            action:
              description: Add / Delete
              type: string
            serviceAccounts:
              description : Service account using which the application will interact with Hadoop system
              type: string
          UserRequest:
            type: object
            properties:
              clusterName:
                description: Name of the Hadoop cluster returned in request Hadoop Service
                type: string
              action:
                description: Add / Delete
                type: string
              userAccounts:
                description: List of users for whom HDFS access neds to be given
                type: string
           StorageRequest:
              type: object
              properties:
                clusterName: 
                  description: Name of the Hadoop cluster
                  type: string
                action:
                  description: Add / Delete
                  type: string
                storage:
                  description: Storage needs to be added or removed
                  type: string
           ComputeRequest:
              type: object
              properties:
                clusterName: 
                  description: Name of the Hadoop cluster
                  type: string
                action:
                  description: Add / Delete
                  type: string
                vCores:
                  description: Number of V-cores to be added or removed
                  type: string      
                memory:
                  description: Memory to be added / removed on the compute node
                  type: string
                disk:
                  description: FAT and FAST disks to be added / removed to compute node
                  type: string
            ManageClusterRequest:
                type: object
                properties:
                  clusterName:
                    description: Name of of the Hadoop Cluster
                    type: string
                  maintenanceAction:
                    description: Delete / Delete All
                    type: string
                  folders:
                    description: List of folders to delete
                    type: array
                    items:
                      type: string
             ClusterFeaturesRequest:
                  type: object
                  properties:
                    clusterName: 
                      description: Name of the Hadoop Cluster
                      type: string
                    requestType:
                      description: Add / Modify / Delete
                      type: string
                    timePeriod:
                      description: Period until when the feature needs to be available
                      format: data-time
                      type: string
                    features:
                      description: List of features which needs to be enables or disabled.
                      Logging
                      Job Scheduling
                      Real-time message consumption
                      BCP replication
                      Performance tuning
                      type: array
                      items: 
                        type: string
                    additionalDetails:
                      description: Any additional details related to features being requested.
                      type: string
               HadoopStorageResponse:
                  type: object
                  properties:
                    clusterName:
                      description: Name of the Hadoop cluster
                      type: string
                    folderStructure:
                      description: The folder structure created in Hadoop Cluster for the requester
                      type: string
                    entitlements: 
                      description: The entitlements provided for authorization purposes
                      type: string
                    edgeNode:
                      description: Information on the edge node
                      type: string
                    storage:
                      description: Storage space allocated. 1 TB by default
                      type: string
                    vCores:
                      description: Number of v-cores allocated for the application
                      type: string
                    yarnQueue:
                      description: Yarn queue name allocated
                      type: string
                 ServiceAccountsResponse:
                    type: object
                    properties:
                      status:
                        description: Success or Failure
                        type: string
                      serviceAccounts:
                        description: List of service accounts added
                        type: array
                        items: 
                            type: string
                  UsersResponse:
                      type: object
                      properties: 
                        status:
                          description: Success or Failure
                          type: string
                        userList:
                          description: List of users added
                          type: array
                          items:
                            type: string
                  StorageResponse:
                      type: object
                      properties:
                        status:
                          description: Success or Failure
                          type: string
                        storage:
                          description: Storage added to the cluster
                          type: string
                   ComputeResponse:
                      type: object
                      properties:
                        status:
                          description: Success of Failure
                          type: string
                        compute:
                          description: V-cores, memory and disk added to the compute
                          type: string
                   ManageClusterResponse:
                      type: object
                      properties:
                        status: 
                          description: Success or Failure
                          type: string
                        folders:
                          description: List of folders deleted:
                          type: array
                          items: 
                            type: string
                    ClusterFeaturesResponse:
                      type: object
                      properties:
                        status: 
                          description: Success or Failure
                          type: string
                        requestType:
                          description: Add / Modify /Delete
                          type: string
                        Features:
                          description: List of features enabled or disabled
                          type: array
                          items:
                            type: string
                 securityDefinitions:
                    default:
                      type: oauth2
                      authorizationUrl: https://hadoopasaservice/authrize
                      flow: implicit
                      scopes: {
                      }
                      
                    
                   
                      
                     
                      
